#! /bin/sh

set -e

CVERSION=`dpkg-query -W -f='${Version}' libcpc-kernel-source`

case "$1" in
  remove|upgrade)
    echo "Removing all DKMS Modules"
    dkms remove -m libcpc -v $CVERSION --all > /dev/null
    echo "Done."
    ;;
esac

exit 0
